### PR TITLE
Todo app

### PR DESCRIPTION
**Pull request by Sooraj-s-98**
## What does this PR do?

Implementation of Appwrite's Database API using Svelte as the UI framework creating a to-do app.

## Test Plan

https://user-images.githubusercontent.com/52352285/196018338-e4176239-9eef-4a1f-b350-a940a00200c0.mov

[repo ](https://github.com/Sooraj-s-98/todo-with-svelte)

## Related PRs and Issues

[issue](https://github.com/appwrite/appwrite/issues/4267)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by Sooraj-s-98** [comment]
@stnguyen90   can you check this PR ?

**Comment by Sooraj-s-98** [comment]
@stnguyen90 can you check PR ?

**Comment by Meldiron** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by stnguyen90** [comment]
@Sooraj-s-98 this looks really cool! How different is this from https://github.com/appwrite/demo-todo-with-svelte? 

Also, the requirement in the issue was to upgrade the existing demos in the repo, but I don't see any of those older files changed 🧐

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
@Sooraj-s-98 this looks really cool! How different is this from https://github.com/appwrite/demo-todo-with-svelte? 

Also, the requirement in the issue was to upgrade the existing demos in the repo, but I don't see any of those older files changed 🧐

**Comment by Sooraj-s-98** [comment]
I am not checked   [https://github.com/appwrite/demo-todo-with-svelte](https://github.com/appwrite/demo-todo-with-svelte) , sorry. you can check the complete commit repo [here.](https://github.com/Sooraj-s-98/todo-with-svelte). two project are different, but both are todo app.

**Comment by christyjacob4** [comment]
Closing this PR considering it deviates from the task mentioned in the issue. Feel free to open a new PR if you decide to work on it again 👍

**Pull request closed without merging**
